### ISSUE TITLE
Safari Bug: css has some bugs

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#28]
- [x] flip button not clickable in safari ?
- [x] only upper half of vis visible for car density and new buildings and agriculture
- [x] as I cannot flip, I could not check the other sides
- [x]  doesn't render the chart properly for export
- [ ] values on hover in energy charts => #270 

copied from below for mobile:
- [x] overlapping flip button with text #271 
- [x] text outside of card on energy primary (footnote issue)
- [x]  building heating top of vis cut of  #271 
- [x]  also unit covered by years #271

**Comment by aeschi** [comment]
![Image](https://user-images.githubusercontent.com/56318362/191261922-73859a01-9e2d-48df-9b18-abc5e4e5ee0c.png)

**Comment by johannahaha** [comment]
I found a problem with the labels on hover :(((

https://user-images.githubusercontent.com/73465311/191723990-d2cbcd1d-00c3-4d8a-9fef-bd9901a02689.mov

**Comment by johannahaha** [comment]
#233

**Comment by aeschi** [comment]
more css bugs for safari mobile - marked in red on images:

- [ ] overlapping flip button with text
- [ ] text outside of card on energy primary
- [ ] building heating top of vis cut of
- [ ] also unit covered by years
- [ ] animal count legend is in middle of postcard behind vis

![IMG_7196](https://user-images.githubusercontent.com/56318362/193063863-34fe61d9-32e1-4b6e-8e8e-34d3813e1733.PNG)
![IMG_7195](https://user-images.githubusercontent.com/56318362/193063874-2b306ad0-966d-4b6b-97d7-eef7c16e09bd.PNG)
![IMG_E14DC5A28726-1](https://user-images.githubusercontent.com/56318362/193063876-44ab2127-dafa-48d8-a4ae-0bd4c7b2d374.jpeg)

**Comment by more-ginger** [comment]
Let's open individual issues instead of having a global one.
